### ISSUE TITLE
Selection to TitleCase doesn’t like ll caps

### ISSUE THREAD

**Issue by LwsBtlr** [bbusschots/macos-quickaction-text#1]
Given THE TREASURE OF THE SIERRA MADRE the titlecase service doesn’t change the case.

I looked at the code, but it looks like it should. Not a jascript writer though, so I just rewrote in as a sed expression (requires gnu sed on macOS and FreeBSD)

Looks like this assumes all caps shouldn’t be changed:

/* Ignore intentional capitalization */
      if (current.substr(1).search(/[A-Z]|\../) > -1) {
        return current
      }

**Comment by bbusschots** [comment]
This is expected behaviour to avoid initialisms like NASA getting messed up.
